import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased overflow-hidden">
        <header className="w-full px-6 py-6  max-w-6xl mx-auto">
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
